{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibghealth",
    "module": "klibghealth",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibghealth-metadata-1.1.1-SNAPSHOT.jar",
          "url": "klibghealth-1.1.1-SNAPSHOT.jar",
          "size": 12398,
          "sha512": "039a399b05cf154476e937a4bb89bbdbab34da928295d3366cab2dd2e40e3fc7adb7b95ce2859fad2de38e7f0600794f15805b988d28110a29dd474a6ac692a1",
          "sha256": "ddf1e4f18d3fa9e888a1d05ea8d9ba344c968bdd48b3e8f42b012abf2ac0bb49",
          "sha1": "a6f4558e0fa2d2727ab8bdebe4e9c270c8119e76",
          "md5": "fa890d36e0548aea98d8fad2c618bf9d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibghealth-kotlin-1.1.1-SNAPSHOT-sources.jar",
          "url": "klibghealth-1.1.1-SNAPSHOT-sources.jar",
          "size": 15459,
          "sha512": "d1830e753ace2aaff8d5fcd3c88ceb4ab50fd92c31d63ddf697acd20d44207b78a52fb57d9d6ebd772d15eb6ad70054059eed75cd59ba563bbad146781a07dc6",
          "sha256": "cba11b6ffe6d537667d2e24c7962dfe01e197cfede754fe53130715d2cb511b8",
          "sha1": "f006c66738ec1b831d82edc9be69a619befc986d",
          "md5": "0f65f553b4c1e1c4e3d9b34cf091e3c8"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibghealth-jvm/1.1.1-SNAPSHOT/klibghealth-jvm-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-jvm",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibghealth-jvm/1.1.1-SNAPSHOT/klibghealth-jvm-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-jvm",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibghealth-jvm/1.1.1-SNAPSHOT/klibghealth-jvm-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-jvm",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibghealth-macosarm64/1.1.1-SNAPSHOT/klibghealth-macosarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-macosarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibghealth-macosarm64/1.1.1-SNAPSHOT/klibghealth-macosarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-macosarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibghealth-macosarm64/1.1.1-SNAPSHOT/klibghealth-macosarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-macosarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    }
  ]
}
