{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibghealth",
    "module": "klibghealth",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibghealth-metadata-1.1.1-SNAPSHOT.jar",
          "url": "klibghealth-1.1.1-SNAPSHOT.jar",
          "size": 12420,
          "sha512": "1c08f953cb78ac7cb32ea83363f76a3216e4bdd113e3d9e1ade6c9457e6a4ff0d396fa4b1f61bf11fd5bc6be6a44da6bc73261f68dc5ac4b93f2b4f2856058e4",
          "sha256": "326407f6b507cf4375a7dd014c6fd3400f482db3076219a687386f9dac176027",
          "sha1": "f28e1f3d0f2b4bd0bfaf58acd758c222113ee333",
          "md5": "3792ab49b1e6b33b7b5805f59136560c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibghealth-kotlin-1.1.1-SNAPSHOT-sources.jar",
          "url": "klibghealth-1.1.1-SNAPSHOT-sources.jar",
          "size": 15500,
          "sha512": "66712741745d7806e9f72228b579967089d3e3ffd128229b63df2ae899e96c55566f18d5e660a22ad8adb779c0739dbe4c9cd196ed29ad65cf63bccb05efb218",
          "sha256": "c6bb4b376cf6150d2523087430397fa286311e2a5f11222301a4dbea773db23f",
          "sha1": "07cb226594180596c4cda6255d37805cbc3f06e8",
          "md5": "72704e41e105e52e7d7058ed3e34bcf8"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibghealth-jvm/1.1.1-SNAPSHOT/klibghealth-jvm-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-jvm",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibghealth-jvm/1.1.1-SNAPSHOT/klibghealth-jvm-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-jvm",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibghealth-jvm/1.1.1-SNAPSHOT/klibghealth-jvm-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-jvm",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibghealth-macosarm64/1.1.1-SNAPSHOT/klibghealth-macosarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-macosarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibghealth-macosarm64/1.1.1-SNAPSHOT/klibghealth-macosarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-macosarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibghealth-macosarm64/1.1.1-SNAPSHOT/klibghealth-macosarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibghealth",
        "module": "klibghealth-macosarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    }
  ]
}
