{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibghealth/1.1.1-SNAPSHOT/klibghealth-1.1.1-SNAPSHOT.module",
    "group": "org.jraf.klibghealth",
    "module": "klibghealth",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibghealth-jvm-1.1.1-SNAPSHOT.jar",
          "url": "klibghealth-jvm-1.1.1-SNAPSHOT.jar",
          "size": 125153,
          "sha512": "91d9f7c3365db26ef116ccdd174bbcf0c7e10f9641fdd15c5fdd52fcd6f2ff9e82be3acebfc8b5bf5f24132fa94ad2bd979b5ff053ae5c2ec4cf3976bd9f253e",
          "sha256": "5ae9c01b6b87e3d45b18b26c25a1cbfe0061c98baaa402537c1a7fa396101b77",
          "sha1": "f98e88ed9124401898f07bd2d38fb62b9df63c25",
          "md5": "463d985de646912f0ea4c5cb22b21a79"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibghealth-jvm-1.1.1-SNAPSHOT.jar",
          "url": "klibghealth-jvm-1.1.1-SNAPSHOT.jar",
          "size": 125153,
          "sha512": "91d9f7c3365db26ef116ccdd174bbcf0c7e10f9641fdd15c5fdd52fcd6f2ff9e82be3acebfc8b5bf5f24132fa94ad2bd979b5ff053ae5c2ec4cf3976bd9f253e",
          "sha256": "5ae9c01b6b87e3d45b18b26c25a1cbfe0061c98baaa402537c1a7fa396101b77",
          "sha1": "f98e88ed9124401898f07bd2d38fb62b9df63c25",
          "md5": "463d985de646912f0ea4c5cb22b21a79"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibghealth-jvm-1.1.1-SNAPSHOT-sources.jar",
          "url": "klibghealth-jvm-1.1.1-SNAPSHOT-sources.jar",
          "size": 15462,
          "sha512": "7845d6b5d604ce4bf64f8fa924ef9c1b447914ea0096fdcf93b6a7cf9b161f98be88c7fa2e635bba7bc095ee304d8c96dc1b7602fc13d6c57e3a625e0b618b84",
          "sha256": "91fa7518a138e2776a54e18a0c1117b4e361bc3e23cece365e9396093b43dbeb",
          "sha1": "ccf381cc554e8e9cc492110dee167b506ab65be9",
          "md5": "d414774eb56a1ecc6392dc268c483eec"
        }
      ]
    }
  ]
}
